import 'package:bright_ui/models/project.dart';
import 'package:flutter/material.dart';

final List projectList = [
  Project(
    id: 'RD1234',
    title: 'Road',
    customColor: Colors.green,
    status: 'On Going',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'Statue',
    customColor: Colors.green,
    status: 'On Going',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'Vikas Bhavan',
    customColor: Colors.green,
    status: 'On Going',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'Church',
    customColor: Colors.green,
    status: 'On Going',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'Secretariant Manitenance',
    customColor: Colors.green,
    status: 'On Going',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'Roofing',
    customColor: Colors.green,
    status: 'Completed',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'City Hall',
    customColor: Colors.green,
    status: 'On Going',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'Road Interlocking',
    customColor: Colors.green,
    status: 'On Going',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'Culvert',
    customColor: Colors.green,
    status: 'On Going',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'House',
    customColor: Colors.green,
    status: 'Completed',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'Shopping Complex',
    customColor: Colors.green,
    status: 'On Going',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'Bridge',
    customColor: Colors.green,
    status: 'Completed',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '16-06-21',
    employeeId: 23,
    tenderId: '123RFG',
  ),
  Project(
    id: 'RD1234',
    title: 'Mall',
    customColor: Colors.green,
    status: 'On Going',
    workDesc: 'Chala - Chovva',
    startDate: '24-05-21',
    dueDate: '26-05-21',
    completedDate: '',
    employeeId: 23,
    tenderId: '123RFG',
  ),
];
